version: '3.9'
services:
  app:
    image: backend-of-e-commerce-website-using-fastapi-and-mysql:40ae610
    ports:
      - "50065:8000"
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://appuser:apppassword@mysql:3306/appdb
      - DB_HOST=mysql
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
      - DB_NAME=appdb

    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppassword
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u appuser -papppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
